// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCny7TCGzjNTehan0XPfSdd0gNdgdeSems',
    appId: '1:562912783113:web:9aec500f7deaa29f8a81d8',
    messagingSenderId: '562912783113',
    projectId: 'registrationform-backend',
    authDomain: 'registrationform-backend.firebaseapp.com',
    storageBucket: 'registrationform-backend.firebasestorage.app',
    measurementId: 'G-6Z7S45JJGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSxeelCPbSe4rySi6hEqaIoIqgg9a9h8',
    appId: '1:562912783113:android:cd7e426693520dba8a81d8',
    messagingSenderId: '562912783113',
    projectId: 'registrationform-backend',
    storageBucket: 'registrationform-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlX_M-D_n1Dw0stsRL7gofjOwdfNuCPdc',
    appId: '1:562912783113:ios:e900fbac07a1200d8a81d8',
    messagingSenderId: '562912783113',
    projectId: 'registrationform-backend',
    storageBucket: 'registrationform-backend.firebasestorage.app',
    iosBundleId: 'com.example.registrationForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlX_M-D_n1Dw0stsRL7gofjOwdfNuCPdc',
    appId: '1:562912783113:ios:e900fbac07a1200d8a81d8',
    messagingSenderId: '562912783113',
    projectId: 'registrationform-backend',
    storageBucket: 'registrationform-backend.firebasestorage.app',
    iosBundleId: 'com.example.registrationForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCny7TCGzjNTehan0XPfSdd0gNdgdeSems',
    appId: '1:562912783113:web:a2861f1bfd5a12008a81d8',
    messagingSenderId: '562912783113',
    projectId: 'registrationform-backend',
    authDomain: 'registrationform-backend.firebaseapp.com',
    storageBucket: 'registrationform-backend.firebasestorage.app',
    measurementId: 'G-D45CHTS86M',
  );
}
